### ISSUE TITLE
The tutorial material link doesnt works

### ISSUE THREAD

**Issue by jprashant21** [AskNowQA/QA-Tutorial#7]
Hi,

The link to the material directs to ESWC 2005 conference page but doesn't provides the link to actual tutorial material.
Can you pls rectify this?

**Comment by geraltofrivia** [comment]
Hello, it seems to be an issue on the side of ESWC organizers. I noticed that our link points to https://2019.eswc-conferences.org/ which is the same link to the conference as indexed in other conference directories including the [ESWC 2019 Guide2Research Page](https://research.com/conference/eswc-2019).

I'll try contacting their webmasters to fix it on their side but there seems to be no alternate link to which I can point at the moment. Thank you for bringing this to our attention.
